{% set name = "rpcq" %}
{% set version = "3.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rpcq-{{ version }}.tar.gz
  sha256: bf21780a1cb1e8676b988c44004d49a168d8937ce2a458c00beb37fa41023684

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - msgpack-python >=0.6,<1.0
    - python >=3.6
    - python-rapidjson
    - pyzmq >=17
    - ruamel.yaml

test:
  imports:
    - rpcq
    - rpcq.external
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The RPC framework and message specification for Rigetti QCS
  dev_url: https://github.com/rigetticomputing/rpcq

extra:
  recipe-maintainers:
    - jmackeyrigetti
    - kilimanjaro
    - notmgsk
    - BastianZim
